site_name: Chris Burchell
site_description: Knowledge Dumping Group
site_author: Chris Burchell
plugins:
  - search
  - blog:
      blog_dir: blog
      post_date_format: long
      post_url_date_format: dd/MM/yyyy
      blog_toc: true
      post_dir: "{blog}/posts"
theme:
  name: material
  favicon: images/favicon/favicon.ico
  # logo: fontawesome/brands/git-alt
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
  language: en
  palette:
    scheme: slate
    primary: green
    accent: deep purple
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/x-hakt
copyright: Established 2024.
repo_url: https://github.com/x-hakt/
repo_name: x-hakt/
icon:
  repo: fontawesome/brands/git-alt
markdown_extensions:
  - abbr 
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
     emoji_index: !!python/name:material.extensions.emoji.twemoji
     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
docs_dir: docs/
# Page tree
nav:
  - Blog: blog/
  - Study Notes:
    - 'study/index.md'
    - AZ-104: 'study/microsoft-az-104.md'
    - eJPTv2: 'study/ejptv2.md'
  - C.V.:
    - Cover Letter: 'cv/coverletter.md'
    - Overview: 'cv/overview.md'
    - Professional Profile: 'cv/profile.md'
    - Prior Experience: 'cv/experience.md'
